# Change these first
owner: ziodotsh # Your GitHub organization or username, where this repository lives
repo: upptime-gearheads.social # The name of this repository
assignees:
  - astravexton
  - electricduck

sites:
  - name: Mastodon
    url: https://gearheads.social
  - name: Mastodon API
    icon: https://em-content.zobj.net/thumbs/60/google/350/gear_2699-fe0f.png
    url: https://gearheads.social/api/v2/instance
  - name: CDN
    icon: https://em-content.zobj.net/thumbs/60/google/350/file-cabinet_1f5c4-fe0f.png
    url: https://cdn.gearheads.social/check.txt
  - name: Relay
    icon: https://em-content.zobj.net/thumbs/60/google/350/chains_26d3-fe0f.png
    url: https://relay.gearheads.social
  - name: Elk
    icon: https://avatars.githubusercontent.com/u/118971678
    url: https://elk.gearheads.social

status-website:
  cname: status.gearheads.social
  css: >
    .logo > div { display: none; }
    .logo > img { height: 32px !important; }
    nav ul li > a {
      border-bottom: 2px solid transparent;
      font-weight: 400;
    }
  logoUrl: https://git.zio.sh/ducky/mastodon-gearheads/raw/commit/00575b48969e4bde37e7ca5255519981e0721d5f/app/javascript/images/logo-symbol-wordmark.svg
  name: Status - Gearheads
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
  #themeUrl: https://cdn.zio.sh/theme/upptime/mastodon-dark.css
  themeUrl: https://b2-euc.gearheads.social/file/zio-euc-public/theme/upptime/mastodon-dark.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
